/********************************************************************
* trackO2Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error trackO2Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabletrackO2Dict();
extern void G__cpp_setup_inheritancetrackO2Dict();
extern void G__cpp_setup_typetabletrackO2Dict();
extern void G__cpp_setup_memvartrackO2Dict();
extern void G__cpp_setup_globaltrackO2Dict();
extern void G__cpp_setup_memfunctrackO2Dict();
extern void G__cpp_setup_functrackO2Dict();
extern void G__set_cpp_environmenttrackO2Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Track.h"
#include "Utils.h"
#include "Constants.h"
#include "Track.h"
#include "Utils.h"
#include "Constants.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__trackO2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__trackO2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__trackO2DictLN_AliceO2;
extern G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBase;
extern G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrack;
extern G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackPar;
extern G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackParCov;

/* STUB derived class for protected member access */
