//
// File generated by rootcint at Thu Dec 17 22:17:00 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME trackO2Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "trackO2Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace AliceO2 {
namespace Base {
namespace Track {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void AliceO2cLcLBasecLcLTrack_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("AliceO2::Base::Track", 0 /*version*/, "./Track.h", 15,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &AliceO2cLcLBasecLcLTrack_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void AliceO2cLcLBasecLcLTrack_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}
}
}

/********************************************************
* trackO2Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabletrackO2Dict();

extern "C" void G__set_cpp_environmenttrackO2Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Track.h");
  G__add_compiledheader("Utils.h");
  G__add_compiledheader("Constants.h");
  G__add_compiledheader("Track.h");
  G__add_compiledheader("Utils.h");
  G__add_compiledheader("Constants.h");
  G__cpp_reset_tagtabletrackO2Dict();
}
#include <new>
extern "C" int G__cpp_dllrevtrackO2Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* AliceO2::Base::Track */
static int G__trackO2Dict_172_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) AliceO2::Base::Track::GetP(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      AliceO2::Base::Track::GetXYZ(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref, (float*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::GetPxPyPz(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref, (float*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::GetPosDir(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref, (float*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::RotateParam(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref, (float) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::PropagateParamTo(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref, (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::PropagateParamBxByBzTo(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref, (float) G__double(libp->para[1])
, (float*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      AliceO2::Base::Track::InvertParam(*(AliceO2::Base::Track::TrackPar*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::Rotate(*(AliceO2::Base::Track::TrackParCov*) libp->para[0].ref, (float) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::PropagateTo(*(AliceO2::Base::Track::TrackParCov*) libp->para[0].ref, (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::PropagateBxByBzTo(*(AliceO2::Base::Track::TrackParCov*) libp->para[0].ref, (float) G__double(libp->para[1])
, (float*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      AliceO2::Base::Track::Invert(*(AliceO2::Base::Track::TrackParCov*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      AliceO2::Base::Track::CheckCovariance(*(AliceO2::Base::Track::TrackParCov*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) AliceO2::Base::Track::TrackPar2Momentum((float*) G__int(libp->para[0]), (float) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trackO2Dict_172_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      AliceO2::Base::Track::g3helx3((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* AliceO2::Base::Track */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunctrackO2Dict {
 public:
  G__Sizep2memfunctrackO2Dict(): p(&G__Sizep2memfunctrackO2Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunctrackO2Dict::*p)();
};

size_t G__get_sizep2memfunctrackO2Dict()
{
  G__Sizep2memfunctrackO2Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancetrackO2Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabletrackO2Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__trackO2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__trackO2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__trackO2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__trackO2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* AliceO2::Base::Track */
static void G__setup_memvarAliceO2cLcLBasecLcLTrack(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrack));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kX=%lldLL",(long long)AliceO2::Base::Track::kX).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kAlpha=%lldLL",(long long)AliceO2::Base::Track::kAlpha).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kY=%lldLL",(long long)AliceO2::Base::Track::kY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kZ=%lldLL",(long long)AliceO2::Base::Track::kZ).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSnp=%lldLL",(long long)AliceO2::Base::Track::kSnp).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kTgl=%lldLL",(long long)AliceO2::Base::Track::kTgl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kQ2Pt=%lldLL",(long long)AliceO2::Base::Track::kQ2Pt).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigY2=%lldLL",(long long)AliceO2::Base::Track::kSigY2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigZY=%lldLL",(long long)AliceO2::Base::Track::kSigZY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigZ2=%lldLL",(long long)AliceO2::Base::Track::kSigZ2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigSnpY=%lldLL",(long long)AliceO2::Base::Track::kSigSnpY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigSnpZ=%lldLL",(long long)AliceO2::Base::Track::kSigSnpZ).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigSnp2=%lldLL",(long long)AliceO2::Base::Track::kSigSnp2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigTglY=%lldLL",(long long)AliceO2::Base::Track::kSigTglY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigTglZ=%lldLL",(long long)AliceO2::Base::Track::kSigTglZ).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigTglSnp=%lldLL",(long long)AliceO2::Base::Track::kSigTglSnp).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigTgl2=%lldLL",(long long)AliceO2::Base::Track::kSigTgl2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigQ2PtY=%lldLL",(long long)AliceO2::Base::Track::kSigQ2PtY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigQ2PtZ=%lldLL",(long long)AliceO2::Base::Track::kSigQ2PtZ).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigQ2PtSnp=%lldLL",(long long)AliceO2::Base::Track::kSigQ2PtSnp).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigQ2PtTgl=%lldLL",(long long)AliceO2::Base::Track::kSigQ2PtTgl).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kSigQ2Pt2=%lldLL",(long long)AliceO2::Base::Track::kSigQ2Pt2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kNParams=%lldLL",(long long)AliceO2::Base::Track::kNParams).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kCovMatSize=%lldLL",(long long)AliceO2::Base::Track::kCovMatSize).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kTrackPSize=%lldLL",(long long)AliceO2::Base::Track::kTrackPSize).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kTrackPCSize=%lldLL",(long long)AliceO2::Base::Track::kTrackPCSize).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA),-1,-2,1,G__FastAllocString(2048).Format("kLabCovMatSize=%lldLL",(long long)AliceO2::Base::Track::kLabCovMatSize).data(),0,(char*)NULL);
   G__memvar_setup((void*)(&AliceO2::Base::Track::kCY2max),102,0,1,-1,-1,-1,1,"kCY2max=",0,(char*)NULL);
   G__memvar_setup((void*)(&AliceO2::Base::Track::kCZ2max),102,0,1,-1,-1,-1,1,"kCZ2max=",0,(char*)NULL);
   G__memvar_setup((void*)(&AliceO2::Base::Track::kCSnp2max),102,0,1,-1,-1,-1,1,"kCSnp2max=",0,(char*)NULL);
   G__memvar_setup((void*)(&AliceO2::Base::Track::kCTgl2max),102,0,1,-1,-1,-1,1,"kCTgl2max=",0,(char*)NULL);
   G__memvar_setup((void*)(&AliceO2::Base::Track::kCQ2Pt2max),102,0,1,-1,-1,-1,1,"kCQ2Pt2max=",0,"Sigma1/Pt<=100 1/GeV");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvartrackO2Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncAliceO2cLcLBasecLcLTrack(void) {
   /* AliceO2::Base::Track */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrack));
   G__memfunc_setup("GetP",368,G__trackO2Dict_172_0_1, 102, -1, -1, 0, 1, 1, 1, 0, "u 'AliceO2::Base::Track::TrackPar' - 11 - track", (char*)NULL, (void*) G__func2void( (float (*)(const AliceO2::Base::Track::TrackPar&))(&AliceO2::Base::Track::GetP) ), 0);
   G__memfunc_setup("GetXYZ",555,G__trackO2Dict_172_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackPar' - 11 - track F - - 0 - xyz", (char*)NULL, (void*) G__func2void( (void (*)(const AliceO2::Base::Track::TrackPar&, float*))(&AliceO2::Base::Track::GetXYZ) ), 0);
   G__memfunc_setup("GetPxPyPz",891,G__trackO2Dict_172_0_3, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackPar' - 11 - track F - - 0 - pxyz", (char*)NULL, (void*) G__func2void( (bool (*)(const AliceO2::Base::Track::TrackPar&, float*))(&AliceO2::Base::Track::GetPxPyPz) ), 0);
   G__memfunc_setup("GetPosDir",881,G__trackO2Dict_172_0_4, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackPar' - 11 - track F - - 0 - posdirp", (char*)NULL, (void*) G__func2void( (bool (*)(const AliceO2::Base::Track::TrackPar&, float*))(&AliceO2::Base::Track::GetPosDir) ), 0);
   G__memfunc_setup("RotateParam",1120,G__trackO2Dict_172_0_5, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackPar' - 1 - track f - - 0 - alpha", (char*)NULL, (void*) G__func2void( (bool (*)(AliceO2::Base::Track::TrackPar&, float))(&AliceO2::Base::Track::RotateParam) ), 0);
   G__memfunc_setup("PropagateParamTo",1623,G__trackO2Dict_172_0_6, 103, -1, -1, 0, 3, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackPar' - 1 - track f - - 0 - xk "
"f - - 0 - b", (char*)NULL, (void*) G__func2void( (bool (*)(AliceO2::Base::Track::TrackPar&, float, float))(&AliceO2::Base::Track::PropagateParamTo) ), 0);
   G__memfunc_setup("PropagateParamBxByBzTo",2184,G__trackO2Dict_172_0_7, 103, -1, -1, 0, 3, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackPar' - 1 - track f - - 0 - xk "
"F - - 10 - b", (char*)NULL, (void*) G__func2void( (bool (*)(AliceO2::Base::Track::TrackPar&, float, const float*))(&AliceO2::Base::Track::PropagateParamBxByBzTo) ), 0);
   G__memfunc_setup("InvertParam",1129,G__trackO2Dict_172_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'AliceO2::Base::Track::TrackPar' - 1 - track", (char*)NULL, (void*) G__func2void( (void (*)(AliceO2::Base::Track::TrackPar&))(&AliceO2::Base::Track::InvertParam) ), 0);
   G__memfunc_setup("Rotate",623,G__trackO2Dict_172_0_9, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackParCov' - 1 - track f - - 0 - alpha", (char*)NULL, (void*) G__func2void( (bool (*)(AliceO2::Base::Track::TrackParCov&, float))(&AliceO2::Base::Track::Rotate) ), 0);
   G__memfunc_setup("PropagateTo",1126,G__trackO2Dict_172_0_10, 103, -1, -1, 0, 3, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackParCov' - 1 - track f - - 0 - xk "
"f - - 0 - b", (char*)NULL, (void*) G__func2void( (bool (*)(AliceO2::Base::Track::TrackParCov&, float, float))(&AliceO2::Base::Track::PropagateTo) ), 0);
   G__memfunc_setup("PropagateBxByBzTo",1687,G__trackO2Dict_172_0_11, 103, -1, -1, 0, 3, 1, 1, 0, 
"u 'AliceO2::Base::Track::TrackParCov' - 1 - track f - - 0 - xk "
"F - - 10 - b", (char*)NULL, (void*) G__func2void( (bool (*)(AliceO2::Base::Track::TrackParCov&, float, const float*))(&AliceO2::Base::Track::PropagateBxByBzTo) ), 0);
   G__memfunc_setup("Invert",632,G__trackO2Dict_172_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'AliceO2::Base::Track::TrackParCov' - 1 - track", (char*)NULL, (void*) G__func2void( (void (*)(AliceO2::Base::Track::TrackParCov&))(&AliceO2::Base::Track::Invert) ), 0);
   G__memfunc_setup("CheckCovariance",1497,G__trackO2Dict_172_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'AliceO2::Base::Track::TrackParCov' - 1 - track", (char*)NULL, (void*) G__func2void( (void (*)(AliceO2::Base::Track::TrackParCov&))(&AliceO2::Base::Track::CheckCovariance) ), 0);
   G__memfunc_setup("TrackPar2Momentum",1692,G__trackO2Dict_172_0_14, 103, -1, -1, 0, 2, 1, 1, 0, 
"F - - 0 - p f - - 0 - alpha", (char*)NULL, (void*) G__func2void( (bool (*)(float*, float))(&AliceO2::Base::Track::TrackPar2Momentum) ), 0);
   G__memfunc_setup("g3helx3",638,G__trackO2Dict_172_0_15, 121, -1, -1, 0, 3, 1, 1, 0, 
"f - - 0 - qfield f - - 0 - step "
"F - - 0 - vect", (char*)NULL, (void*) G__func2void( (void (*)(float, float, float*))(&AliceO2::Base::Track::g3helx3) ), 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunctrackO2Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaltrackO2Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_functrackO2Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__trackO2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__trackO2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__trackO2DictLN_AliceO2 = { "AliceO2" , 110 , -1 };
G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBase = { "AliceO2::Base" , 110 , -1 };
G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrack = { "AliceO2::Base::Track" , 110 , -1 };
G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA = { "AliceO2::Base::Track::$" , 101 , -1 };
G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackPar = { "AliceO2::Base::Track::TrackPar" , 99 , -1 };
G__linked_taginfo G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackParCov = { "AliceO2::Base::Track::TrackParCov" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabletrackO2Dict() {
  G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__trackO2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__trackO2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__trackO2DictLN_AliceO2.tagnum = -1 ;
  G__trackO2DictLN_AliceO2cLcLBase.tagnum = -1 ;
  G__trackO2DictLN_AliceO2cLcLBasecLcLTrack.tagnum = -1 ;
  G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA.tagnum = -1 ;
  G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackPar.tagnum = -1 ;
  G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackParCov.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabletrackO2Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_AliceO2);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_AliceO2cLcLBase);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrack),0,-1,0,(char*)NULL,G__setup_memvarAliceO2cLcLBasecLcLTrack,G__setup_memfuncAliceO2cLcLBasecLcLTrack);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLdA);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackPar);
   G__get_linked_tagnum_fwd(&G__trackO2DictLN_AliceO2cLcLBasecLcLTrackcLcLTrackParCov);
}
extern "C" void G__cpp_setuptrackO2Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuptrackO2Dict()");
  G__set_cpp_environmenttrackO2Dict();
  G__cpp_setup_tagtabletrackO2Dict();

  G__cpp_setup_inheritancetrackO2Dict();

  G__cpp_setup_typetabletrackO2Dict();

  G__cpp_setup_memvartrackO2Dict();

  G__cpp_setup_memfunctrackO2Dict();
  G__cpp_setup_globaltrackO2Dict();
  G__cpp_setup_functrackO2Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunctrackO2Dict();
  return;
}
class G__cpp_setup_inittrackO2Dict {
  public:
    G__cpp_setup_inittrackO2Dict() { G__add_setup_func("trackO2Dict",(G__incsetup)(&G__cpp_setuptrackO2Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_inittrackO2Dict() { G__remove_setup_func("trackO2Dict"); }
};
G__cpp_setup_inittrackO2Dict G__cpp_setup_initializertrackO2Dict;

